#!/bin/bash

# Build static libraries for nimbbl_mobile_kit_ios_webview_sdk
# This script extracts static libraries from the existing framework

set -e

echo "Building static libraries for nimbbl_mobile_kit_ios_webview_sdk..."

# Clean previous builds
rm -rf static_lib

# Create static_lib directory
mkdir -p static_lib/Headers

# Extract the binary from the framework
echo "Extracting binary from framework..."
cp nimbbl_mobile_kit_ios_webview_sdk.framework/nimbbl_mobile_kit_ios_webview_sdk static_lib/libnimbbl_mobile_kit_ios_webview_sdk.a

# Copy headers if they exist
if [ -d "nimbbl_mobile_kit_ios_webview_sdk.framework/Headers" ]; then
    echo "Copying headers..."
    cp -R nimbbl_mobile_kit_ios_webview_sdk.framework/Headers/* static_lib/Headers/
fi

# Create module map
echo "Creating module map..."
cat > static_lib/module.modulemap << 'EOF'
framework module nimbbl_mobile_kit_ios_webview_sdk {
  umbrella header "nimbbl_mobile_kit_ios_webview_sdk-Swift.h"
  
  export *
  module * { export * }
}
EOF

# Create Swift bridging header
echo "Creating Swift bridging header..."
cat > static_lib/Headers/nimbbl_mobile_kit_ios_webview_sdk-Swift.h << 'EOF'
//
//  nimbbl_mobile_kit_ios_webview_sdk-Swift.h
//  nimbbl_mobile_kit_ios_webview_sdk
//
//  Generated by Swift
//

#ifndef nimbbl_mobile_kit_ios_webview_sdk_Swift_h
#define nimbbl_mobile_kit_ios_webview_sdk_Swift_h

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <WebKit/WebKit.h>

//! Project version number for nimbbl_mobile_kit_ios_webview_sdk.
FOUNDATION_EXPORT double nimbbl_mobile_kit_ios_webview_sdkVersionNumber;

//! Project version string for nimbbl_mobile_kit_ios_webview_sdk.
FOUNDATION_EXPORT const unsigned char nimbbl_mobile_kit_ios_webview_sdkVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <nimbbl_mobile_kit_ios_webview_sdk/PublicHeader.h>

#endif /* nimbbl_mobile_kit_ios_webview_sdk_Swift_h */
EOF

echo "Static library build complete!"
echo "Static library location: static_lib/libnimbbl_mobile_kit_ios_webview_sdk.a"
echo "Headers location: static_lib/Headers/"
