//
//  nimbbl_mobile_kit_ios_webview_sdk-Swift.h
//  nimbbl_mobile_kit_ios_webview_sdk
//
//  Generated by Swift
//

#ifndef nimbbl_mobile_kit_ios_webview_sdk_Swift_h
#define nimbbl_mobile_kit_ios_webview_sdk_Swift_h

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <WebKit/WebKit.h>

//! Project version number for nimbbl_mobile_kit_ios_webview_sdk.
FOUNDATION_EXPORT double nimbbl_mobile_kit_ios_webview_sdkVersionNumber;

//! Project version string for nimbbl_mobile_kit_ios_webview_sdk.
FOUNDATION_EXPORT const unsigned char nimbbl_mobile_kit_ios_webview_sdkVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <nimbbl_mobile_kit_ios_webview_sdk/PublicHeader.h>

#endif /* nimbbl_mobile_kit_ios_webview_sdk_Swift_h */
